### ISSUE TITLE
Warning on version & plugins

### ISSUE THREAD

**Issue by arya-coding** [ppedro74/IBMWatson-playground#1]
Hi,

I've encountered some difficulties with your program :

- In the MainForm.cs, at line 71, there is twice "ServiceUrl"
- After building it for the first time, I've got one warning about a conflict on different versions of the same assembly.

> warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file.

- When I run it, I've got :
> 14:09:59.764>Warning>>Loaded: System.Net.Http, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
14:09:59.767>Warning>>...Expected 4.0.0.0

However, on the project references, the version of System.Net.http is 4.0.0.0.
So I'm removing it from the references, and reinstalling the 4.0.0.0 through NuGet, and when building the project, I have : 

> Warning	NU1605	Detected package downgrade: System.Net.Http from 4.1.0 to 4.0.0. Reference the package directly from the project to select a different version. 
 IBMWatsonServicesTest -> IBM.WatsonDeveloperCloud.TextToSpeech.v1 2.11.0 -> NETStandard.Library 1.6.0 -> System.Net.Http (>= 4.1.0) 
 IBMWatsonServicesTest -> System.Net.Http (>= 4.0.0)	IBMWatsonServicesTest	D:\....\IBMWatson-playground-master\IBMWatsonServicesTest\IBMWatsonServicesTest.csproj	1	

EDIT : In the readme, for the "Workaround/Solution:" the quotes are missing from the original solution on the post your mentionned. 
Thank you,

**Comment by ppedro74** [comment]
In the MainForm.cs, at line 71, there is twice "ServiceUrl" 
Is intentional it creates an empty watson.ini like this:
```
; Watson Services
[TextToSpeechService]
ApiKey=put_here_the_api_key

;ServiceUrl=https://gateway-wdc.watsonplatform.net/text-to-speech/api
ServiceUrl=put_here_the_service_url

```
The first ServiceUrl is a comment/example of what serviceUrl look like, some people take out the https others add more stuff.

Did you download my project without change it and it does not work ? 

Please tell me your VS and Nuget versions ?

**Comment by arya-coding** [comment]
Alright my bad.

Yes I just imported your project and couldn't make it work but I'm not used to C# and Windows Programming.

However, I tried the solution on the issue you mentionned : https://github.com/dotnet/corefx/issues/11100#issuecomment-246469893

And it's finally working ! I have to try with the other IBM Watson modules.
